"""SVG output generation for pen plotters."""

import svgwrite
from pathlib import Path
from typing import List, Tuple, Optional, Union
from dataclasses import dataclass

from .curves import ProcessedPath, BezierSegment
from .config import ConversionConfig


@dataclass
class SVGDocument:
    """Represents an SVG document with metadata.

    Attributes:
        content: SVG content as string
        width: Document width in specified units
        height: Document height in specified units
        units: Units (mm, px, etc.)
        path_count: Number of paths in the document
        total_path_length: Approximate total path length
    """

    content: str
    width: float
    height: float
    units: str
    path_count: int
    total_path_length: float


def create_svg(
    paths: List[ProcessedPath],
    width: float,
    height: float,
    config: ConversionConfig,
    units: str = "mm",
    source_width: Optional[int] = None,
    source_height: Optional[int] = None,
) -> SVGDocument:
    """Create an SVG document from processed paths.

    Args:
        paths: List of processed paths
        width: Output width in specified units
        height: Output height in specified units
        config: Conversion configuration
        units: Output units (mm, px, in)
        source_width: Original image width for scaling
        source_height: Original image height for scaling

    Returns:
        SVGDocument with content and metadata
    """
    # Create SVG drawing
    size = (f"{width}{units}", f"{height}{units}")

    # Set viewBox to match source dimensions if provided
    if source_width and source_height:
        viewbox = f"0 0 {source_width} {source_height}"
    else:
        viewbox = f"0 0 {width} {height}"

    dwg = svgwrite.Drawing(size=size, viewBox=viewbox)

    # Add metadata comment
    dwg.add(dwg.comment("Generated by raster2vector - https://github.com/cleihgeber/fantastic-octo-fishstick"))

    # Create a group for all paths
    group = dwg.g(
        id="drawing",
        stroke=config.stroke_color,
        stroke_width=config.stroke_width,
        fill="none",
        stroke_linecap="round",
        stroke_linejoin="round",
    )

    total_length = 0.0

    for i, processed_path in enumerate(paths):
        path_element = _create_path_element(dwg, processed_path, f"path_{i}")
        if path_element is not None:
            group.add(path_element)
            total_length += _estimate_path_length(processed_path)

    dwg.add(group)

    return SVGDocument(
        content=dwg.tostring(),
        width=width,
        height=height,
        units=units,
        path_count=len(paths),
        total_path_length=total_length,
    )


def _create_path_element(
    dwg: svgwrite.Drawing, processed_path: ProcessedPath, path_id: str
) -> Optional[svgwrite.path.Path]:
    """Create an SVG path element from a processed path.

    Args:
        dwg: SVG drawing object
        processed_path: Processed path data
        path_id: ID for the path element

    Returns:
        SVG path element or None if path is empty
    """
    if processed_path.uses_bezier:
        return _create_bezier_path(dwg, processed_path.bezier_segments, path_id, processed_path.is_closed)
    elif processed_path.points:
        return _create_polyline_path(dwg, processed_path.points, path_id, processed_path.is_closed)
    return None


def _create_bezier_path(
    dwg: svgwrite.Drawing,
    segments: List[BezierSegment],
    path_id: str,
    is_closed: bool,
) -> svgwrite.path.Path:
    """Create an SVG path from Bezier segments.

    Args:
        dwg: SVG drawing object
        segments: List of Bezier segments
        path_id: ID for the path element
        is_closed: Whether the path should be closed

    Returns:
        SVG path element
    """
    if not segments:
        return None

    # Build path data string
    d = []

    # Move to start of first segment
    d.append(f"M {segments[0].p0[0]:.3f} {segments[0].p0[1]:.3f}")

    for seg in segments:
        # Cubic Bezier curve command
        d.append(
            f"C {seg.p1[0]:.3f} {seg.p1[1]:.3f}, "
            f"{seg.p2[0]:.3f} {seg.p2[1]:.3f}, "
            f"{seg.p3[0]:.3f} {seg.p3[1]:.3f}"
        )

    if is_closed:
        d.append("Z")

    path_data = " ".join(d)
    return dwg.path(d=path_data, id=path_id)


def _create_polyline_path(
    dwg: svgwrite.Drawing,
    points: List[Tuple[float, float]],
    path_id: str,
    is_closed: bool,
) -> svgwrite.path.Path:
    """Create an SVG path from a polyline.

    Args:
        dwg: SVG drawing object
        points: List of (x, y) coordinates
        path_id: ID for the path element
        is_closed: Whether the path should be closed

    Returns:
        SVG path element
    """
    if not points:
        return None

    # Build path data string
    d = [f"M {points[0][0]:.3f} {points[0][1]:.3f}"]

    for point in points[1:]:
        d.append(f"L {point[0]:.3f} {point[1]:.3f}")

    if is_closed:
        d.append("Z")

    path_data = " ".join(d)
    return dwg.path(d=path_data, id=path_id)


def _estimate_path_length(processed_path: ProcessedPath) -> float:
    """Estimate the total length of a processed path.

    Args:
        processed_path: Processed path

    Returns:
        Estimated length in source units
    """
    import numpy as np

    if processed_path.uses_bezier:
        # Approximate Bezier length using control polygon
        total = 0.0
        for seg in processed_path.bezier_segments:
            points = [seg.p0, seg.p1, seg.p2, seg.p3]
            for i in range(len(points) - 1):
                dx = points[i + 1][0] - points[i][0]
                dy = points[i + 1][1] - points[i][1]
                total += np.sqrt(dx * dx + dy * dy)
        return total * 0.75  # Rough correction factor

    elif processed_path.points:
        total = 0.0
        for i in range(len(processed_path.points) - 1):
            dx = processed_path.points[i + 1][0] - processed_path.points[i][0]
            dy = processed_path.points[i + 1][1] - processed_path.points[i][1]
            total += np.sqrt(dx * dx + dy * dy)
        return total

    return 0.0


def save_svg(svg_doc: SVGDocument, output_path: Union[str, Path]) -> None:
    """Save an SVG document to file.

    Args:
        svg_doc: SVG document to save
        output_path: Output file path
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(svg_doc.content)


def paths_to_gcode(
    paths: List[ProcessedPath],
    width: float,
    height: float,
    feed_rate: float = 1000,
    z_up: float = 5.0,
    z_down: float = 0.0,
) -> str:
    """Convert paths to basic G-code for CNC/plotter control.

    This generates simple G-code suitable for basic pen plotters
    and CNC machines. For more advanced machines, use specialized
    software to process the SVG output.

    Args:
        paths: List of processed paths
        width: Work area width in mm
        height: Work area height in mm
        feed_rate: Movement speed in mm/min
        z_up: Z height when pen is up
        z_down: Z height when pen is down

    Returns:
        G-code as string
    """
    lines = [
        "; Generated by raster2vector",
        f"; Work area: {width}mm x {height}mm",
        "G21 ; Set units to millimeters",
        "G90 ; Absolute positioning",
        f"G0 Z{z_up} ; Pen up",
        "G0 X0 Y0 ; Home position",
        "",
    ]

    for path in paths:
        if path.uses_bezier:
            # Flatten Bezier curves to line segments for G-code
            points = _flatten_bezier_path(path.bezier_segments)
        else:
            points = path.points or []

        if not points:
            continue

        # Move to start with pen up
        x, y = points[0]
        lines.append(f"G0 X{x:.3f} Y{y:.3f} ; Move to start")
        lines.append(f"G1 Z{z_down} F{feed_rate} ; Pen down")

        # Draw path
        for point in points[1:]:
            x, y = point
            lines.append(f"G1 X{x:.3f} Y{y:.3f}")

        # Pen up after path
        lines.append(f"G0 Z{z_up} ; Pen up")
        lines.append("")

    # End
    lines.extend(
        [
            "G0 X0 Y0 ; Return home",
            "M2 ; End program",
        ]
    )

    return "\n".join(lines)


def _flatten_bezier_path(
    segments: List[BezierSegment], steps_per_segment: int = 10
) -> List[Tuple[float, float]]:
    """Flatten Bezier curves to line segments.

    Args:
        segments: List of Bezier segments
        steps_per_segment: Number of line segments per Bezier curve

    Returns:
        List of points
    """
    import numpy as np

    points = []

    for seg in segments:
        for i in range(steps_per_segment + 1):
            t = i / steps_per_segment
            # Cubic Bezier formula
            t2 = t * t
            t3 = t2 * t
            mt = 1 - t
            mt2 = mt * mt
            mt3 = mt2 * mt

            x = mt3 * seg.p0[0] + 3 * mt2 * t * seg.p1[0] + 3 * mt * t2 * seg.p2[0] + t3 * seg.p3[0]
            y = mt3 * seg.p0[1] + 3 * mt2 * t * seg.p1[1] + 3 * mt * t2 * seg.p2[1] + t3 * seg.p3[1]

            # Avoid duplicate points
            if not points or (abs(x - points[-1][0]) > 0.001 or abs(y - points[-1][1]) > 0.001):
                points.append((x, y))

    return points
